name: Nightly Release

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  delete_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Delete release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete_release: true
          tag_name: 2.0.0-nightly
      - name: Retrieve version
        run: |
          echo "TAG_NAME=$(npm version prerelease --preid=next)" >> $GITHUB_OUTPUT
        id: version
  nightly:
    needs: delete_tag
    uses: hmmachadocx/fork-ast-cli-javascript-wrapper/.github/workflows/release-beta.yml@main
    with:
      tag: ${{ steps.version.outputs.TAG_NAME }}
    secrets: inherit
