name: Nightly Release

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  delete_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Delete release
        uses: actions/delete-package-versions@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: 'packages'
          package-name: 'fork-ast-cli-javascript-wrapper'
          package-type: 'npm'
          delete-only-pre-release-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
